# Targeted rebuild of cilium-cni with OKE chaining support.

ARG CILIUM_BUILDER_IMAGE=quay.io/cilium/cilium-builder:67e01eec68a14c27433621d42a5ae2050d7eed64@sha256:d14c823c9348710886265b6a96b9e9cc274f20c8e610af375845424b42dfab07
ARG CILIUM_BASE_IMAGE=quay.io/cilium/cilium:v1.19.4

FROM --platform=${BUILDPLATFORM} ${CILIUM_BUILDER_IMAGE} AS builder

ARG TARGETARCH
ARG TARGETOS=linux

WORKDIR /go/src/github.com/cilium/cilium

RUN --mount=type=bind,readwrite,target=/go/src/github.com/cilium/cilium \
    --mount=type=cache,target=/root/.cache \
    --mount=type=cache,target=/go/pkg \
    GOARCH=${TARGETARCH} GOOS=${TARGETOS} \
    go build \
      -o /tmp/cilium-cni \
      ./plugins/cilium-cni/cmd/

FROM ${CILIUM_BASE_IMAGE}

COPY --from=builder /tmp/cilium-cni /opt/cni/bin/cilium-cni
